resources:
  - type: storage.v1.bucket
    name: sls-sls-dev-1517979948823
  - type: cloudfunctions.v1beta2.function
    name: sls-dev-web
    properties:
      location: us-central1
      availableMemoryMb: 256
      timeout: 60s
      function: test1
      sourceArchiveUrl: >-
        gs://sls-sls-dev-1517979948823/serverless/sls/dev/1517988120886-2018-02-07T07:22:00.886Z/sls.zip
      httpsTrigger:
        url: null
